/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author bananalemon
 */


import java.util.ArrayList;
import java.util.List;
import system.Tiket;

public class FormTiket extends javax.swing.JFrame {

    
    public Tiket tiket;
    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        tiket = new Tiket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_group_b = new javax.swing.ButtonGroup();
        b_group_k = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        field_nik = new javax.swing.JTextField();
        field_nama = new javax.swing.JTextField();
        field_alamat = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        radio_berangkat_pagi = new javax.swing.JRadioButton();
        radio_berangkat_siang = new javax.swing.JRadioButton();
        radio_berangkat_sore = new javax.swing.JRadioButton();
        radio_kelas_ekonomi = new javax.swing.JRadioButton();
        radio_kelas_eksekutif = new javax.swing.JRadioButton();
        radio_kelas_premium = new javax.swing.JRadioButton();
        radio_kelas_sleeper = new javax.swing.JRadioButton();
        cb_layanan_makan = new javax.swing.JCheckBox();
        cb_layanan_snack = new javax.swing.JCheckBox();
        cb_layanan_selimut = new javax.swing.JCheckBox();
        button_submit = new javax.swing.JButton();
        field_tanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Tanggal    ( dd/mm/yyyy )");

        jLabel5.setText("Berangkat");

        jLabel6.setText("Kelas");

        jLabel7.setText("Layanan");

        b_group_b.add(radio_berangkat_pagi);
        radio_berangkat_pagi.setText("Pagi");

        b_group_b.add(radio_berangkat_siang);
        radio_berangkat_siang.setText("Siang");

        b_group_b.add(radio_berangkat_sore);
        radio_berangkat_sore.setText("Sore");

        b_group_k.add(radio_kelas_ekonomi);
        radio_kelas_ekonomi.setText("Ekonomi");
        radio_kelas_ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_kelas_ekonomiActionPerformed(evt);
            }
        });

        b_group_k.add(radio_kelas_eksekutif);
        radio_kelas_eksekutif.setText("Executive");
        radio_kelas_eksekutif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_kelas_eksekutifActionPerformed(evt);
            }
        });

        b_group_k.add(radio_kelas_premium);
        radio_kelas_premium.setText("Premium");
        radio_kelas_premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_kelas_premiumActionPerformed(evt);
            }
        });

        b_group_k.add(radio_kelas_sleeper);
        radio_kelas_sleeper.setText("Sleeper");
        radio_kelas_sleeper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_kelas_sleeperActionPerformed(evt);
            }
        });

        cb_layanan_makan.setText("Makan");

        cb_layanan_snack.setText("Snacks");

        cb_layanan_selimut.setText("Selimut");

        button_submit.setBackground(new java.awt.Color(51, 153, 0));
        button_submit.setForeground(new java.awt.Color(255, 255, 255));
        button_submit.setText("Submit");
        button_submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_layanan_makan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_kelas_ekonomi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_layanan_snack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_kelas_premium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_layanan_selimut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_kelas_eksekutif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(radio_kelas_sleeper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(radio_berangkat_sore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(radio_berangkat_siang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(button_submit, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_nama)
                            .addComponent(field_nik)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_tanggal)
                            .addComponent(field_alamat))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(radio_berangkat_pagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(field_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(field_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radio_berangkat_siang)
                    .addComponent(radio_berangkat_sore)
                    .addComponent(radio_berangkat_pagi))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(radio_kelas_ekonomi)
                    .addComponent(radio_kelas_premium)
                    .addComponent(radio_kelas_sleeper)
                    .addComponent(radio_kelas_eksekutif))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_layanan_makan)
                        .addComponent(cb_layanan_snack)
                        .addComponent(cb_layanan_selimut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(button_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void radio_kelas_ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_kelas_ekonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_kelas_ekonomiActionPerformed

    private void radio_kelas_eksekutifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_kelas_eksekutifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_kelas_eksekutifActionPerformed

    private void radio_kelas_premiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_kelas_premiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_kelas_premiumActionPerformed

    private void radio_kelas_sleeperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_kelas_sleeperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_kelas_sleeperActionPerformed

    private void button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_submitActionPerformed
        // TODO add your handling code here:
        
        int nik = Integer.parseInt(field_nik.getText());
        String nama = field_nama.getText();
        String alamat = field_alamat.getText();
        String tanggal_berangkat = field_tanggal.getText();
        
        int rv_berangkat = 0 ;
        if(radio_berangkat_pagi.isSelected()){
            rv_berangkat = 1;
        } else if (radio_berangkat_siang.isSelected()) {
            rv_berangkat = 2;
        } else if (radio_berangkat_sore.isSelected()){
            rv_berangkat = 3;
        } else {
            System.out.println("no data found");
        }
        
        int rv_kelas = 0;
        if(radio_kelas_ekonomi.isSelected()){
            rv_kelas = 1;
        } else if (radio_kelas_premium.isSelected()){
            rv_kelas= 2;
        } else if (radio_kelas_eksekutif.isSelected()){
            rv_kelas= 3;
        } else if (radio_kelas_sleeper.isSelected()){
            rv_kelas= 4;
        } else {
            System.out.println("no data found");
        }
        
        List <String> list_layanan = new ArrayList<>();
        
        if(cb_layanan_makan.isSelected()){
            list_layanan.add("1");
        } 
        if (cb_layanan_snack.isSelected()) {
            list_layanan.add("2");
        }
        if(cb_layanan_selimut.isSelected()){
            list_layanan.add("3");
        }
        
        tiket.setNik(nik);
        tiket.setNama(nama);
        tiket.setAlamat(alamat);
        tiket.setTanggal_berangkat(tanggal_berangkat);
        tiket.setBerangkat(String.valueOf(rv_berangkat));
        tiket.setKelas(String.valueOf(rv_kelas));
        tiket.setLayanan(String.join(",", list_layanan));
        
        View overview = new View(tiket);
        overview.setVisible(true);
        
        setVisible(false);
    
       
        
       /* 
        String join_list_layanan = String.join(",", list_layanan);
        String format = nik + "$" + nama + "$" + alamat + "$" + tanggal_berangkat + "$" + rv_berangkat + "$" + rv_kelas + "$" + join_list_layanan;
        
        FileChooserSave.setDialogTitle("Choose Directory to save file");
        FileChooserLoad.setName( nama + ".txt" );
        
        int user_select = FileChooserSave.showSaveDialog(this);
        if ( user_select == JFileChooser.APPROVE_OPTION){
            
            try {
                
                FileWriter fw = new FileWriter(FileChooserSave.getSelectedFile());
                fw.write(format);
                fw.close();
            } catch ( Exception e){
                System.out.println("Problem Accessing the File " + e.getStackTrace());
            }
        }
         
    }//GEN-LAST:event_button_submitActionPerformed
*/
}
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup b_group_b;
    private javax.swing.ButtonGroup b_group_k;
    private javax.swing.JButton button_submit;
    private javax.swing.JCheckBox cb_layanan_makan;
    private javax.swing.JCheckBox cb_layanan_selimut;
    private javax.swing.JCheckBox cb_layanan_snack;
    private javax.swing.JTextField field_alamat;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_nik;
    private javax.swing.JTextField field_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton radio_berangkat_pagi;
    private javax.swing.JRadioButton radio_berangkat_siang;
    private javax.swing.JRadioButton radio_berangkat_sore;
    private javax.swing.JRadioButton radio_kelas_ekonomi;
    private javax.swing.JRadioButton radio_kelas_eksekutif;
    private javax.swing.JRadioButton radio_kelas_premium;
    private javax.swing.JRadioButton radio_kelas_sleeper;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
