/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import system.Tiket;
import gui.FormTiket;
import java.io.FileWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author bananalemon
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form Overview
     */
    public View(Tiket tiket) {
        initComponents();
        
        this.label_nik.setText(Integer.toString(tiket.getNik()));
        this.label_nama.setText(tiket.getNama());
        this.label_alamat.setText(tiket.getAlamat());
        this.label_tanggal_berangkat.setText(tiket.getTanggal_berangkat());
        
        int conv_berangkat = Integer.parseInt(tiket.getBerangkat());
        if(conv_berangkat == 1){
            radio_berangkat_pagi.setSelected(true);
        } else if (conv_berangkat == 2 ){
            radio_berangkat_siang.setSelected(true);
        } else if (conv_berangkat == 3 ){
            radio_berangkat_sore.setSelected(true);
        } else {
            System.out.println("nilai tidak ada dalam pilihan");
        }
        
        int conv_kelas = Integer.parseInt(tiket.getKelas());
        if(conv_kelas == 1){
            radio_kelas_ekonomi.setSelected(true);
        } else if (conv_kelas == 2 ){
            radio_kelas_premium.setSelected(true);
        } else if (conv_kelas == 3 ){
            radio_kelas_eksekutif.setSelected(true);
        } else if (conv_kelas == 4){
            radio_kelas_sleeper.setSelected(true);
        } else {
            System.out.println("nilai tidak ada dalam pilihan");
        }
        
        String check_layanan = tiket.getLayanan();
        if(check_layanan.contains("1")){
            cb_makan.setSelected(true);
        }
        if(check_layanan.contains("2")){
            cb_snack.setSelected(true);
        }
        if(check_layanan.contains("3")){
            cb_selimut.setSelected(true);
        }
        
        if(conv_kelas == 1){
            tiket.setHarga_tiket(50000d * 0.1);
        } else if ( conv_kelas == 2) {
            tiket.setHarga_tiket(50000d*0.2);
        } else if ( conv_kelas == 3) {
            tiket.setHarga_tiket(50000d*0.3);
        } else if ( conv_kelas == 4) {
            tiket.setHarga_tiket(50000d*0.4);
        }
        
        double harga_l = 0;
        if(cb_makan.isSelected()){
            harga_l += 20000;
        }
        if(cb_snack.isSelected()){
            harga_l += 10000;
        }
        if(cb_selimut.isSelected()){
            harga_l += 5000;
        }
        
        tiket.setHarga_layanan(harga_l);
        
        
            
        
        this.label_harga_tiket.setText(Double.toString(tiket.getHarga_tiket()));
        this.label_harga_layanan.setText(Double.toString(tiket.getHarga_layanan()));
        
        tiket.setHarga_total(50000d + harga_l + tiket.getHarga_tiket());
        this.label_total_harga.setText(Double.toString(tiket.getHarga_total()));
        
        
        
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_b = new javax.swing.ButtonGroup();
        bg_k = new javax.swing.ButtonGroup();
        fcsave = new javax.swing.JFileChooser();
        fcload = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        radio_berangkat_pagi = new javax.swing.JRadioButton();
        radio_berangkat_siang = new javax.swing.JRadioButton();
        radio_berangkat_sore = new javax.swing.JRadioButton();
        radio_kelas_premium = new javax.swing.JRadioButton();
        radio_kelas_eksekutif = new javax.swing.JRadioButton();
        radio_kelas_sleeper = new javax.swing.JRadioButton();
        radio_kelas_ekonomi = new javax.swing.JRadioButton();
        cb_makan = new javax.swing.JCheckBox();
        cb_snack = new javax.swing.JCheckBox();
        cb_selimut = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        label_nik = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_alamat = new javax.swing.JLabel();
        label_harga_tiket = new javax.swing.JLabel();
        label_tanggal_berangkat = new javax.swing.JLabel();
        label_harga_layanan = new javax.swing.JLabel();
        label_total_harga = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        button_quit = new javax.swing.JButton();

        fcsave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Tanggal Berangkat");

        jLabel5.setText("Berangkat");

        jLabel6.setText("Kelas");

        jLabel7.setText("Layanan");

        bg_b.add(radio_berangkat_pagi);
        radio_berangkat_pagi.setText("Pagi");

        bg_b.add(radio_berangkat_siang);
        radio_berangkat_siang.setText("Siang");
        radio_berangkat_siang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_berangkat_siangActionPerformed(evt);
            }
        });

        bg_b.add(radio_berangkat_sore);
        radio_berangkat_sore.setText("Sore");
        radio_berangkat_sore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_berangkat_soreActionPerformed(evt);
            }
        });

        bg_k.add(radio_kelas_premium);
        radio_kelas_premium.setText("Premium");

        bg_k.add(radio_kelas_eksekutif);
        radio_kelas_eksekutif.setText("Executive");

        bg_k.add(radio_kelas_sleeper);
        radio_kelas_sleeper.setText("Sleeper");

        bg_k.add(radio_kelas_ekonomi);
        radio_kelas_ekonomi.setText("Ekonomi");
        radio_kelas_ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_kelas_ekonomiActionPerformed(evt);
            }
        });

        cb_makan.setText("Makan");

        cb_snack.setText("Snacks");

        cb_selimut.setText("Selimut");

        jLabel8.setText("Harga Tiket");

        jLabel9.setText("Harga Layanan");

        jLabel10.setText("Total Harga");

        label_nik.setText("{{ nik }}");

        label_nama.setText("{{ nama }}");

        label_alamat.setText("{{ alamat }}");

        label_harga_tiket.setText("{{ harga tiket }}");

        label_tanggal_berangkat.setText("{{ tanggal berangkat }}");

        label_harga_layanan.setText("{{ harga layanan }}");

        label_total_harga.setText("{{ total harga }}");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        button_quit.setBackground(new java.awt.Color(204, 0, 51));
        button_quit.setForeground(new java.awt.Color(255, 255, 255));
        button_quit.setText("Quit");
        button_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_quit))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_harga_layanan, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(label_harga_tiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_tanggal_berangkat, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_makan)
                            .addComponent(radio_kelas_ekonomi)
                            .addComponent(radio_berangkat_pagi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_snack)
                            .addComponent(radio_kelas_premium)
                            .addComponent(radio_berangkat_siang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_selimut)
                            .addComponent(radio_kelas_eksekutif)
                            .addComponent(radio_berangkat_sore))
                        .addGap(18, 18, 18)
                        .addComponent(radio_kelas_sleeper)
                        .addGap(68, 68, 68))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radio_berangkat_pagi, radio_berangkat_sore});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {label_alamat, label_harga_layanan, label_harga_tiket, label_nama, label_nik, label_tanggal_berangkat, label_total_harga});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_quit, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(label_nik))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(label_nama))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_alamat)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tanggal_berangkat)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(radio_berangkat_pagi)
                    .addComponent(radio_berangkat_siang)
                    .addComponent(radio_berangkat_sore))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio_kelas_premium)
                        .addComponent(radio_kelas_eksekutif)
                        .addComponent(radio_kelas_sleeper))
                    .addComponent(radio_kelas_ekonomi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_selimut)
                    .addComponent(cb_snack)
                    .addComponent(cb_makan)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(label_harga_tiket))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(label_harga_layanan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(label_total_harga))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(button_quit))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_quit, jButton1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_kelas_ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_kelas_ekonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_kelas_ekonomiActionPerformed

    private void radio_berangkat_soreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_berangkat_soreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_berangkat_soreActionPerformed

    private void radio_berangkat_siangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_berangkat_siangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_berangkat_siangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       Tiket tiket = new Tiket();
       
       String save = tiket.getNik() + "$" + tiket.getNama() + "$" + tiket.getAlamat() + "$" +
               tiket.getTanggal_berangkat() + "$" + tiket.getBerangkat() + "$" + tiket.getKelas()
               + "$" + tiket.getLayanan()  + "$" + tiket.getHarga_tiket() + "$" + tiket.getHarga_layanan()
               + "$" + tiket.getHarga_total();
       
       fcsave.setDialogTitle("choose save directory..");
       fcload.setName(tiket.getNama() + ".txt");
       
       int user_select = fcsave.showSaveDialog(this);
        if ( user_select == JFileChooser.APPROVE_OPTION){
            
            try {
                
                FileWriter fw = new FileWriter(fcsave.getSelectedFile());
                fw.write(save);
                fw.close();
            } catch ( Exception e){
                System.out.println("Problem Accessing the File " + e.getStackTrace());
            }
        }


        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_b;
    private javax.swing.ButtonGroup bg_k;
    private javax.swing.JButton button_quit;
    private javax.swing.JCheckBox cb_makan;
    private javax.swing.JCheckBox cb_selimut;
    private javax.swing.JCheckBox cb_snack;
    private javax.swing.JFileChooser fcload;
    private javax.swing.JFileChooser fcsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_harga_layanan;
    private javax.swing.JLabel label_harga_tiket;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nik;
    private javax.swing.JLabel label_tanggal_berangkat;
    private javax.swing.JLabel label_total_harga;
    private javax.swing.JRadioButton radio_berangkat_pagi;
    private javax.swing.JRadioButton radio_berangkat_siang;
    private javax.swing.JRadioButton radio_berangkat_sore;
    private javax.swing.JRadioButton radio_kelas_ekonomi;
    private javax.swing.JRadioButton radio_kelas_eksekutif;
    private javax.swing.JRadioButton radio_kelas_premium;
    private javax.swing.JRadioButton radio_kelas_sleeper;
    // End of variables declaration//GEN-END:variables
}
